export const PROFILE_FETCH_BEGIN = 'PROFILE_FETCH_BEGIN'; 
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'; 
export const PROFILE_FETCH_ERROR = 'PROFILE_FETCH_ERROR'; 

export const CARD_POINTER_UPDATE = 'CARD_POINTER_UPDATE'; 
export const CARD_INFO_OPENED = 'CARD_INFO_OPENED'; 
export const CARD_INFO_CLOSED = 'CARD_INFO_CLOSED'; 

export const PHOTO_UPDATED = 'PHOTO_UPDATED'; 

export const SETTINGS_FETCH_BEGIN = 'SETTINGS_FETCH_BEGIN'; 
export const SETTINGS_FETCH_SUCCESS = 'SETTINGS_FETCH_SUCCESS'; 
export const SETTINGS_FETCH_ERROR = 'SETTINGS_FETCH_ERROR'; 
export const SETTINGS_UPDATED = 'SETTINGS_UPDATED'; 