export const PROFILE_FETCH_BEGIN = 'PROFILE_FETCH_BEGIN'; 
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'; 
export const PROFILE_FETCH_ERROR = 'PROFILE_FETCH_ERROR'; 

export const CARD_POINTER_UPDATE = 'CARD_POINTER_UPDATE'; 
export const CARD_INFO_OPENED = 'CARD_INFO_OPENED'; 
export const CARD_INFO_CLOSED = 'CARD_INFO_CLOSED'; 